version: '{build}'
branches:
  only:
  - master
  - /^v\d+(?:\.\d+)?$/
  - /[\b_]validate\b/
skip_tags: true
skip_commits:
  files:
    - doc/*
    - '**/*.md'
    - .vsts-ci.yml
nuget:
  disable_publish_on_pr: true
image: Visual Studio 2017
configuration: Release
environment:
  VisualStudioVersion: 15.0
before_build:
- ps: >-
    cd src

    dotnet restore
build_script:
- ps: msbuild /nologo /m /t:build,pack
test_script:
- cmd: >-
    cd ..

    SET testdir=bin\Microsoft.VisualStudio.Validation.Tests\%configuration%\net452\

    "%userprofile%\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe"
    -register:user
    -target:"%xunit20%\xunit.console.x86.exe"
    -targetargs:"%testdir%Microsoft.VisualStudio.Validation.Tests.dll -noshadow -parallel all -html %testdir%testresults.html -xml %testdir%testresults.xml -appveyor -notrait TestCategory=FailsInCloudTest -nologo"
    -returntargetcode
    -excludebyattribute:*.ExcludeFromCodeCoverage*
    -excludebyfile:*\*Designer.cs
    -filter:"+[Microsoft.VisualStudio.Validation]*"
    -hideskipped:All
    -output:%testdir%code_coverage.xml

    SET PATH=C:\Python34;C:\Python34\Scripts;%PATH%

    pip install codecov

    codecov -f "%testdir%code_coverage.xml"

    cd src\Microsoft.VisualStudio.Validation.Tests

    dotnet test --no-build -f netcoreapp1.0
artifacts:
- path: bin\Microsoft.VisualStudio.Validation\%configuration%\*.nupkg
  name: NuGet Package
