version: 1.0.{build}
skip_tags: true
image: Visual Studio 2015
configuration: Release
environment:
  VisualStudioVersion: 14.0
cache:
- '%USERPROFILE%\.nuget\packages -> **\project.json'
- 'obj\tools -> tools\**'
before_build:
- ps: .\init.ps1
build:
  project: src\Microsoft.VisualStudio.Validation.sln
  parallel: true
  verbosity: minimal
test_script:
- cmd: >-
    %xunit20%\xunit.console.x86 "bin\Release\Microsoft.VisualStudio.Validation.Tests.Desktop.dll" "bin\Release\Profile259\Microsoft.VisualStudio.Validation.Tests.Portable.dll" -noshadow -parallel all -html bin\release\testresults.html -xml bin\release\testresults.xml -appveyor -notrait "TestCategory=FailsInCloudTest" -nologo
artifacts:
- path: bin\**\*.nupkg
  name: NuGet Package
