steps:
- script: dotnet restore src  /v:m /bl:"$(Build.ArtifactStagingDirectory)/build_logs/restore.binlog"
  displayName: dotnet restore

# Use msbuild instead of dotnet build because MicroBuild plugins don't work on dotnet build.
- task: VSBuild@1
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  inputs:
    vsVersion: 16.0
    msbuildArgs: /t:build,pack /m /bl:"$(Build.ArtifactStagingDirectory)/build_logs/build.binlog"
    configuration: $(BuildConfiguration)
    platform: $(BuildPlatform)
  displayName: msbuild

- script: dotnet build src --no-restore -c $(BuildConfiguration) /v:m /bl:"$(Build.ArtifactStagingDirectory)/build_logs/build.binlog"
  condition: ne(variables['Agent.OS'], 'Windows_NT')
  displayName: dotnet build

- script: dotnet pack src --no-build -c $(BuildConfiguration) /v:m /bl:"$(Build.ArtifactStagingDirectory)/build_logs/pack.binlog"
  condition: ne(variables['Agent.OS'], 'Windows_NT')
  displayName: dotnet pack

- script: dotnet test src --no-build -c $(BuildConfiguration) -f net452 --filter "TestCategory!=FailsInCloudTest" -v n -l trx /p:CollectCoverage=true
  displayName: dotnet test -f net452
  continueOnError: true
  condition: eq(variables['Agent.OS'], 'Windows_NT')
- script: dotnet test src --no-build -c $(BuildConfiguration) -f netcoreapp1.0 --filter "TestCategory!=FailsInCloudTest" -v n -l trx # Avoid code coverage on netcoreapp1.0 (see https://github.com/tonerdo/coverlet/issues/466)
  displayName: dotnet test -f netcoreapp1.0
  continueOnError: true
- script: dotnet test src --no-build -c $(BuildConfiguration) -f netcoreapp2.2 --filter "TestCategory!=FailsInCloudTest" -v n -l trx /p:CollectCoverage=true
  displayName: dotnet test -f netcoreapp2.2
  continueOnError: true

- task: PublishTestResults@2
  displayName: Publish test results
  inputs:
    testRunner: VSTest
    #mergeTestResults: true
    testResultsFormat: trx
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: true
  condition: succeededOrFailed()

- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage results to Azure DevOps
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation: '**/coverage.cobertura.xml'
  condition: succeededOrFailed()

- bash: bash <(curl -s https://codecov.io/bash)
  displayName: Publish code coverage results to codecov.io
  condition: and(succeededOrFailed(), ne(variables['system.collectionId'], '011b8bdf-6d56-4f87-be0d-0092136884d9'))

- task: CopyFiles@1
  inputs:
    Contents: |
      obj/**/project.assets.json
    TargetFolder: $(Build.ArtifactStagingDirectory)/projectAssetsJson
  displayName: Collecting project.assets.json artifacts
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/projectAssetsJson
    ArtifactName: projectAssetsJson-$(Agent.JobName)
    ArtifactType: Container
  displayName: Publish projectAssetsJson artifacts
  condition: succeededOrFailed()
