trigger:
  branches:
    include: ["master"]
  paths:
    exclude: [".github", "doc", "*.md"]

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU

jobs:
- job: Windows
  pool: VSEng-MicroBuildVS2019
  steps:
  - template: azure-pipeline.microbuild.before.yml
  - template: install-dependencies.yml

  - script: |
      dotnet tool install --tool-path .. nbgv
      ..\nbgv cloud
    workingDirectory: src
    displayName: Set build number

  - template: dotnet.yml
  - template: azure-pipeline.microbuild.after.yml
  - template: collect-deployables.yml
  - template: collect-logs.yml
